name: build HEAD
on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo "VERSION=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: chmod +x gradlew
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - run: ./gradlew build
        env:
          MOD_VERSION: ${{ steps.vars.outputs.VERSION }}
      - uses: actions/upload-artifact@v2
        with:
          name: build ${{ steps.vars.outputs.VERSION }}
          path: "./**/build/libs/**.jar"
